### ISSUE TITLE
ADC: wrong init macro

### ISSUE THREAD

**Issue by Remmirad** [RIOT-OS/rust-riot-sys#29]
I think this: https://github.com/RIOT-OS/rust-riot-sys/blob/4a1a63090cf6942246052847db142988fecd1658/build.rs#L274 
needs to be `ADC_LINE`?  (see [RIOT-doc](https://doc.riot-os.org/group__drivers__periph__adc.html))

**Comment by chrysn** [comment]
This is fixed now in https://github.com/RIOT-OS/rust-riot-sys/pull/34.
